// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjshMCjtp0wyLifaPDe1S5f1U1Vp3KKPA',
    appId: '1:1069118844420:web:371377e0c27f3654770f51',
    messagingSenderId: '1069118844420',
    projectId: 'dormibemm',
    authDomain: 'dormibemm.firebaseapp.com',
    storageBucket: 'dormibemm.firebasestorage.app',
    measurementId: 'G-10SFPXDR6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWRv6ClUQ2yuaoGjJRUTXJsvEcOJAtpF8',
    appId: '1:1069118844420:android:72f734de9e20115c770f51',
    messagingSenderId: '1069118844420',
    projectId: 'dormibemm',
    storageBucket: 'dormibemm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRocw0qNEZR5f-X-5HZPLl-mOtEGbvqhE',
    appId: '1:1069118844420:ios:93d58563e766f1ef770f51',
    messagingSenderId: '1069118844420',
    projectId: 'dormibemm',
    storageBucket: 'dormibemm.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRocw0qNEZR5f-X-5HZPLl-mOtEGbvqhE',
    appId: '1:1069118844420:ios:93d58563e766f1ef770f51',
    messagingSenderId: '1069118844420',
    projectId: 'dormibemm',
    storageBucket: 'dormibemm.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjshMCjtp0wyLifaPDe1S5f1U1Vp3KKPA',
    appId: '1:1069118844420:web:bbb288c1f7a44416770f51',
    messagingSenderId: '1069118844420',
    projectId: 'dormibemm',
    authDomain: 'dormibemm.firebaseapp.com',
    storageBucket: 'dormibemm.firebasestorage.app',
    measurementId: 'G-5TTGTD4P9K',
  );
}
